spring:
  datasource:
    # H2 in-memory database configuration for testing
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # Disable Liquibase for testing
  liquibase:
    enabled: false

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Include Swagger profile
  profiles:
    include: swagger

# Server configuration
server:
  port: 8080